development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: jeocrowd4s
  suffix: development
  username: root
  password: toor

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: jeocrowd4s
  suffix: production
  username: root
  password: 123