development: &development
  protocol: http
  host: localhost
  port: 5984
  prefix: jeocrowd4s
  suffix: development
  username: root
  password: toor

test:
  <<: *development
  suffix: test

# run heroku config --long to get details
production:
  protocol: https
  host: app1613810.heroku.cloudant.com
  port: 443
  prefix: jeocrowd4s
  suffix: production
  username: app1613810.heroku
  password: DCnQxbDfV7HoJ2tVl4T0TBlp
