development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jeocrowd_development
  pool: 5
  username: devuser
  password: devpass
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jeocrowd_test
  pool: 5
  username: devuser
  password: devpass
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jeocrowd4s_production
  pool: 5
  username: user
  password: -wee
  host: 127.0.0.1

